[build] Add basic clang-cl support
visualboyadvance-m/visualboyadvance-m pull request #1018
Opened 2022-10-09 06:28 UTC by Steelskin

XAudio2 is disabled because the included header needs to be updated to be parseable by clang.

2022-10-12 01:17 UTC, rkitover requested changes

2022-10-15 20:35 UTC, Steelskin commented on CMakeLists.txt
> +    add_definitions(-DNO_XAUDIO2)
I filed a bug and added a reference here.

2022-10-15 20:35 UTC, Steelskin commented on CMakeLists.txt
> +if(CMAKE_C_COMPILER_ID STREQUAL Clang AND CMAKE_CXX_COMPILER_ID STREQUAL Clang AND NOT MSVC)
Added a TODO

2022-10-15 20:35 UTC, Steelskin commented on cmake/Set-Toolchain-vcpkg.cmake
> -    if(WIN32 AND NOT CMAKE_GENERATOR MATCHES "Visual Studio")
Reverted with the extra check. Yes, it's how I'm setting the compiler. I actually use CMakeKits, which does it for me.

2022-10-15 21:11 UTC, ZachBacon commented
> XAudio2 is disabled because the included header needs to be updated to be parseable by clang.

Technically we could remove the xaudio2 header, especially if it's an msvc build, also mingw now includes that header too.

2022-10-15 21:33 UTC, Steelskin commented
> > XAudio2 is disabled because the included header needs to be updated to be parseable by clang.
> 
> Technically we could remove the xaudio2 header, especially if it's an msvc build, also mingw now includes that header too.

The included xaudio2 header is pre-windows-8. Since the API changed in Windows 8, our code does not compile with the new version of the header included in the Windows SDK.

2022-10-15 22:25 UTC, merged

2022-10-16 06:41 UTC, Squall-Leonhart commented
we can use xaudio 2.8 and have people install the xaudio installer i made if they use 7.