optional using xss to suspend screensaver
visualboyadvance-m/visualboyadvance-m pull request #1098
Opened 2023-03-17 05:22 UTC by multiSnow

suspend screensaver when game is started/resumed.
restart screensaver when game is unloaded/paused.
(screensaver will be restarted automatically if the whole program disconnected from the X server)

use ENABLE_XSS cmake option to enable xss.
by default, ENABLE_XSS is OFF thus nothing changed (using `XResetScreenSaver` to reset screensaver everytime the joystick botton pressed).

2023-03-27 15:54 UTC, rkitover commented
Hi, sorry I missed this, our server was down last week.

Please join our discord if you'd like to discuss this there.

I would prefer this to be a runtime option, like a checkbox in display setting for "suspend screensaver", we'd do any necessary adjustments for other platforms as well.

2023-03-27 18:19 UTC, multiSnow commented
The checkbox is added in 'UI Settings...'.

2023-03-27 23:42 UTC, rkitover requested changes
This looks fantastic, thank you, I am requesting one minor change and then I will merge it.

2023-03-27 23:42 UTC, rkitover commented on CMakeLists.txt
> +    option(ENABLE_XSS "Check XSS support in the wxWidgets port" OFF)
I don't think this is necessary, we can just automatically use it when available.

2023-03-27 23:47 UTC, rkitover commented on src/wx/guiinit.cpp
> +        { getcbb("SuspendScreenSaver", gopts.suspend_screensaver); }
We should hide the checkbox on Windows and mac until we have an implementation for those platforms. But you don't have to do this, I can do this after I merge your change.

2023-03-28 16:30 UTC, rkitover commented
This is merged, thank you for your contribution!

I made one minor change to also hide the checkbox under Wayland.

2023-03-28 16:30 UTC, closed without merging