Move build options to their own file
visualboyadvance-m/visualboyadvance-m pull request #1238
Opened 2024-03-10 00:21 UTC by Steelskin

This moves all build options to their own file to clean up the main CMakeLists.txt. In addition, this upgrades the minimum required CMake version and changes the build to use CMAKE_MSVC_RUNTIME_LIBRARY rather than hardcoding the MSVC ABI flag.

2024-03-10 08:02 UTC, rkitover commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.19)
That's Nov 2020, 3.5 years ago, good enough for me.

2024-03-10 08:44 UTC, rkitover commented
I left a few comments, everything else looks fine to me. I will check on those couple of things I was going to research.

2024-03-11 00:03 UTC, rkitover requested changes

2024-03-11 00:36 UTC, Steelskin commented on cmake/Options.cmake
> +if((WIN32 AND (X64 OR X86)) OR APPLE) # winsparkle/sparkle
Done.

2024-03-11 00:36 UTC, Steelskin commented on CMakeLists.txt
>  if(VBAM_STATIC)
Done

2024-03-11 00:36 UTC, Steelskin commented on CMakeLists.txt
>  if(WIN32 AND ((NOT (MINGW AND MSYS)) OR CMAKE_TOOLCHAIN_FILE MATCHES mxe) AND NOT CMAKE_TOOLCHAIN_FILE MATCHES vcpkg)
Done

2024-03-11 00:36 UTC, Steelskin commented on cmake/Options.cmake
> +    if(SFML_STATIC_LIBRARIES AND SFML_NETWORK_LIBRARY_STATIC_DEBUG AND SFML_SYSTEM_LIBRARY_STATIC_DEBUG)
Done

2024-03-11 00:36 UTC, Steelskin commented on CMakeLists.txt
>  if(WIN32 AND ((NOT (MINGW AND MSYS)) OR CMAKE_TOOLCHAIN_FILE MATCHES mxe) AND NOT CMAKE_TOOLCHAIN_FILE MATCHES vcpkg)
Done

2024-03-11 00:36 UTC, Steelskin commented on CMakeLists.txt
>  if(VBAM_STATIC)
Done

2024-03-11 00:36 UTC, Steelskin commented on cmake/Options.cmake
> +    if(SFML_STATIC_LIBRARIES AND SFML_NETWORK_LIBRARY_STATIC_DEBUG AND SFML_SYSTEM_LIBRARY_STATIC_DEBUG)
Done

2024-03-11 00:36 UTC, Steelskin commented on cmake/Options.cmake
> +if((WIN32 AND (X64 OR X86)) OR APPLE) # winsparkle/sparkle
I wasn't sure this was what you meant.

2024-03-11 00:36 UTC, Steelskin commented on cmake/Options.cmake
> +# gcc lto produces buggy binaries for 64 bit mingw
It's actually working on UCRT64 with clang but it can stay as is for now.

2024-03-11 00:59 UTC, Steelskin commented on cmake/Options.cmake
> +if((WIN32 AND (X64 OR X86)) OR APPLE) # winsparkle/sparkle
As discussed offline, I replaced the check for `UPSTREAM_RELEASE`

2024-03-11 01:38 UTC, merged